version: '2'
services:
  node01:
    image: percona/percona-xtradb-cluster
    container_name: ${COMPOSE_PROJECT_NAME}_pxc_node01
    networks:
      pxc_network:
        ipv4_address: ${NODE_1_IP_ADDRESS}
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN:

  nodeN:
    image: percona/percona-xtradb-cluster
#    container_name: ${COMPOSE_PROJECT_NAME}_pxc_nodeN
    networks:
      - pxc_network
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN: ${NODE_1_IP_ADDRESS}
    depends_on:
      - node01

networks:
  pxc_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

